# Generated by Django 5.0.6 on 2024-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='name',
            field=models.CharField(default='Default', max_length=150),
        ),
    ]
